---
version: 2.1
parameters:
  stage:
    type: string
    default: "QA"

workflows:
  build:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
    environment:
      TEST_STAGE: << pipeline.parameters.stage >>
    steps:
      - checkout
      - run:
          name: Run test
          command: ./test.py
